> /home/neuro/Downloads/models/cacam_models/camkii/rxn_Kcam_init1/rxn_process.py(35)<module>()
-> f.write(rxn_part)
(Pdb) Traceback (most recent call last):
  File "../rxn_process.py", line 35, in <module>
    f.write(rxn_part)
  File "../rxn_process.py", line 35, in <module>
    f.write(rxn_part)
  File "/home/neuro/miniconda2/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/neuro/miniconda2/lib/python2.7/bdb.py", line 67, in dispatch_line
    self.user_line(frame)
  File "/home/neuro/miniconda2/lib/python2.7/pdb.py", line 158, in user_line
    self.interaction(frame, None)
  File "/home/neuro/miniconda2/lib/python2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "/home/neuro/miniconda2/lib/python2.7/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
IOError: [Errno 9] Bad file descriptor
10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990
1000
1010
1020
1030
1040
1050
1060
1070
1080
1090
1100
1110
1120
1130
1140
1150
1160
1170
1180
1190
1200
1210
1220
1230
1240
1250
1260
1270
1280
1290
1300
1310
1401
1411
1421
1443
1563
1573
1583
1593
1603
1613
1623
1709
1773
1783
1793
1803
1813
1823
1833
2050
